### ISSUE TITLE
No rule to make target `tinyobjloader/tiny_obj_loader.cc

### ISSUE THREAD

**Issue by shomedas** [ramonsaraiva/cuda-convexhull#1]
When I do make(in cuda-convexhull-master directory) I get:

make: **\* No rule to make target `tinyobjloader/tiny_obj_loader.cc', needed by`build/objects/tiny_obj_loader.o'.  Stop.

I found that there is no tiny tiny_obj_loader.cc in tinyobjloader folder.

The given a.out runs fine giving all the gpu details. I use ubuntu 14.04, 64bit on nvidia -gtx 960

**Comment by ramonsaraiva** [comment]
The issue is that you need to clone this repository inside the project [https://github.com/syoyo/tinyobjloader](https://github.com/syoyo/tinyobjloader).
