### ISSUE TITLE
what is the version of tinyobj to be used?

### ISSUE THREAD

**Issue by shomedas** [ramonsaraiva/cuda-convexhull#2]
i tried compiling the code after copying tinyobjloader from the given location. But it gives errors like:

no matching function for call to ‘LoadObj(std::vectortinyobj::shape_t&, std::vectortinyobj::material_t&, const char_&, const char_)’

what version of the tinyobjloader needs to be used?

**Comment by ramonsaraiva** [comment]
Try using a version around Nov 30, 2014.

**Comment by shomedas** [comment]
git only has current version. How can i get the version of nov 2014. can you kindly provide a link to it?

**Comment by ramonsaraiva** [comment]
You can git reset to a commit around that date, that's all you can do imo.

**Comment by shomedas** [comment]
sorry for asking that silly question. i found it from the older versions from git
