### ISSUE TITLE
are the `pkg-config --cflags-only-I sdl` `pkg-config --libs-only-L sdl` necessary

### ISSUE THREAD

**Issue by shomedas** [ramonsaraiva/cuda-convexhull#5]
I compiled the code using:

g++ -I.  -o build/bin/convexhull build/objects/tiny_obj_loader.o build/objects/camera.o build/objects/scene.o build/objects/input.o build/objects/convexhull.o build/objects/main.o -lSDL -lSOIL -lGLEW -lGLU -lGL -lglut

However the makefile has declarations like:
pkg-config --cflags-only-I sdl` `pkg-config --libs-only-L sdl

Is it needed?

**Comment by ramonsaraiva** [comment]
If you compiled the code and it worked like you expected or how it is supposed to work, then probably not! Sorry but it was just a college project and i don't quite remember everything i made there. Googling a little bit will be healthy.
